OrdererOrgs:
  - Name: Orderer
    Domain: authenticator.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.authenticator.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.authenticator.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Auth
    Domain: Auth.authenticator.com
    Template:
      Count: 1
    Users:
      Count: 1
